### ISSUE TITLE
Organize the accelerator options within a yaml file

### ISSUE THREAD

**Issue by DomInvivo** [datamol-io/graphium#314]
```yaml
accelerator:
  type: ipu
  datamodule:
    ipu_dataloader_training_opts:
      mode: async
      max_num_nodes_per_graph: 20 # train max nodes: 20, max_edges: 54
      max_num_edges_per_graph: 60

    ipu_dataloader_inference_opts:
      mode: async
      max_num_nodes_per_graph: 20 # valid max nodes: 51, max_edges: 118
      max_num_edges_per_graph: 120
      # test-dev max nodes: 50, max_edges: 116
      # test-challenge max nodes: 51, max_edges: 106

  predictor:
    optim_kwargs:
      loss_scaling: 1024

  ipu.config:
    - deviceIterations(1) # IPU would require large batches to be ready for the model.
    - replicationFactor(8)
    # - enableProfiling("graph_analyser")       # The folder where the profile will be stored
    # - enableExecutableCaching("pop_compiler_cache")
    - TensorLocations.numIOTiles(128)
    - _Popart.set("defaultBufferingDepth", 256)
```
