### ISSUE TITLE
Outdated Instructions in README

### ISSUE THREAD

**Issue by WenkelF** [datamol-io/graphium#464]
The section **Running an experiment** uses an incorrect argument `dataset`, e.g.,

`graphium-train dataset=toymix model=gcn`

This is inconsistent with the hydra setup in `expts/hydra-configs/main.yaml`:

```
defaults:

  # Accelerators
  - accelerator: cpu

  # Pre-training/fine-tuning
  - architecture: toymix
  - tasks: toymix
  - training: toymix

  # Benchmarking
  - model: gcn

  # Specializations
  - training/accelerator: ${training}_${accelerator}
  - training/model: ${training}_${model}
```
